spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartvms
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: YourSuperSecretKeyHereMakeItLongEnoughForSecurity12345678901234567890
  expiration: 86400000  # 24 hours in milliseconds

# Admin credentials
admin:
  username: admin123
  password: aman 